# Generated by Django 6.0.4 on 2026-05-01 18:24

import django.db.models.deletion
import school.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLiaison',
            fields=[
                ('id_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=school.models.CodeLiaison.generate_code, max_length=8, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(default=school.models.CodeLiaison.default_expiration)),
                ('utilise', models.BooleanField(default=False)),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_liaison', to='school.eleves')),
            ],
            options={
                'verbose_name': 'Code de liaison',
                'verbose_name_plural': 'Codes de liaison',
                'db_table': 'codes_liaison',
            },
        ),
    ]
