# Generated by Django 6.0.3 on 2026-06-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_codeliaison'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='push_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
