# Generated by Django 6.0.4 on 2026-06-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type_notif',
            field=models.CharField(choices=[('rappel', 'Rappel'), ('rapport', 'Rapport'), ('badge', 'Badge'), ('alerte', 'Alerte'), ('promo', 'Promotion'), ('coach', 'Coach')], max_length=20),
        ),
    ]
