# Generated by Django 6.0.4 on 2026-06-09 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_notifications_type_notif'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroLecons',
            fields=[
                ('id_lecon', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('points_cles', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('ia', 'IA'), ('fallback', 'Fallback')], default='ia', max_length=10)),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_cours', models.ForeignKey(blank=True, help_text='Cours de référence suggéré pour approfondir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micro_lecons', to='school.cours')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_lecons', to='school.eleves')),
                ('id_lacune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micro_lecons', to='school.lacunes')),
                ('id_matiere', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='micro_lecons', to='school.matieres')),
            ],
            options={
                'verbose_name': 'Micro-leçon',
                'verbose_name_plural': 'Micro-leçons',
                'db_table': 'micro_lecons',
                'ordering': ['-date_creation'],
            },
        ),
    ]
