# Generated by Django 6.0.4 on 2026-06-10 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_microlecons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defis',
            fields=[
                ('id_defi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('titre', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('type_cible', models.CharField(choices=[('sessions_semaine', 'Sessions terminées (semaine)'), ('revisions_semaine', 'Révisions quotidiennes (semaine)'), ('streak', 'Série de jours'), ('exercices_total', 'Exercices cumulés'), ('score_max', 'Meilleure note /20')], max_length=30)),
                ('seuil', models.PositiveIntegerField(default=1)),
                ('recompense_xp', models.PositiveIntegerField(default=50)),
                ('periode', models.CharField(choices=[('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire'), ('permanent', 'Permanent')], default='hebdomadaire', max_length=15)),
                ('icone', models.CharField(blank=True, default='flag', max_length=40)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Défi',
                'verbose_name_plural': 'Défis',
                'db_table': 'defis',
            },
        ),
        migrations.CreateModel(
            name='EleveDefis',
            fields=[
                ('id_eleve_defi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode_cle', models.CharField(max_length=20)),
                ('progression', models.PositiveIntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('recompense_reclamee', models.BooleanField(default=False)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('id_defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='school.defis')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defis', to='school.eleves')),
            ],
            options={
                'verbose_name': 'Défi élève',
                'verbose_name_plural': 'Défis élèves',
                'db_table': 'eleve_defis',
                'constraints': [models.UniqueConstraint(fields=('id_eleve', 'id_defi', 'periode_cle'), name='uq_eleve_defi_periode')],
            },
        ),
        migrations.CreateModel(
            name='MicroRevisions',
            fields=[
                ('id_revision', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_jour', models.DateField()),
                ('completee', models.BooleanField(default=False)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions_quotidiennes', to='school.eleves')),
                ('id_epreuve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='school.epreuves')),
            ],
            options={
                'verbose_name': 'Micro-révision',
                'verbose_name_plural': 'Micro-révisions',
                'db_table': 'micro_revisions',
                'ordering': ['-date_jour'],
                'constraints': [models.UniqueConstraint(fields=('id_eleve', 'date_jour'), name='uq_revision_jour')],
            },
        ),
    ]
