# Generated by Django 6.0.4 on 2026-06-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_defis_elevedefis_microrevisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='microrevisions',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='microrevisions',
            name='source',
            field=models.CharField(blank=True, default='ia', max_length=10),
        ),
    ]
