# Generated by Django 6.0.4 on 2026-06-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_microrevisions_rappel_envoye_microrevisions_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuves',
            name='corrige',
            field=models.TextField(blank=True, help_text="Corrigé global rédigé par l'enseignant.", null=True),
        ),
    ]
