# Generated by Django 6.0.4 on 2026-06-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_epreuves_corrige'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text="Cours au format PDF, consultable par l'élève.", null=True, upload_to='cours_pdf/'),
        ),
        migrations.AddField(
            model_name='epreuves',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text="Sujet/annale au format PDF, consultable par l'élève.", null=True, upload_to='epreuves_pdf/'),
        ),
    ]
