# Generated by Django 6.0.4 on 2026-06-11 05:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_cours_fichier_pdf_epreuves_fichier_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id_avis', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('id_cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='school.cours')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='school.eleves')),
                ('id_epreuve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='school.epreuves')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'db_table': 'avis',
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('id_cours__isnull', False)), fields=('id_eleve', 'id_cours'), name='uq_avis_eleve_cours'), models.UniqueConstraint(condition=models.Q(('id_epreuve__isnull', False)), fields=('id_eleve', 'id_epreuve'), name='uq_avis_eleve_epreuve'), models.CheckConstraint(condition=models.Q(models.Q(('id_cours__isnull', False), ('id_epreuve__isnull', True)), models.Q(('id_cours__isnull', True), ('id_epreuve__isnull', False)), _connector='OR'), name='avis_cours_xor_epreuve')],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id_favori', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='school.cours')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='school.eleves')),
                ('id_epreuve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='school.epreuves')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'db_table': 'favoris',
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('id_cours__isnull', False)), fields=('id_eleve', 'id_cours'), name='uq_favori_eleve_cours'), models.UniqueConstraint(condition=models.Q(('id_epreuve__isnull', False)), fields=('id_eleve', 'id_epreuve'), name='uq_favori_eleve_epreuve')],
            },
        ),
    ]
