# Generated by Django 6.0.4 on 2026-06-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_avis_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuves',
            name='corrige_pdf',
            field=models.FileField(blank=True, help_text="Corrigé au format PDF, visible par l'élève après composition.", null=True, upload_to='epreuves_corriges/'),
        ),
    ]
