# Generated by Django 6.0.4 on 2026-06-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_epreuves_corrige_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='notif_publication_envoyee',
            field=models.BooleanField(default=False, help_text='Empêche de re-notifier les élèves à la publication.'),
        ),
        migrations.AddField(
            model_name='epreuves',
            name='notif_publication_envoyee',
            field=models.BooleanField(default=False, help_text='Empêche de re-notifier les élèves pour ce contenu.'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type_notif',
            field=models.CharField(choices=[('rappel', 'Rappel'), ('rapport', 'Rapport'), ('badge', 'Badge'), ('alerte', 'Alerte'), ('promo', 'Promotion'), ('coach', 'Coach'), ('nouveau_contenu', 'Nouveau contenu')], max_length=20),
        ),
    ]
