# Generated by Django 6.0.4 on 2026-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_cours_notif_publication_envoyee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleves',
            name='systeme',
            field=models.CharField(choices=[('francophone', 'Francophone'), ('anglophone', 'Anglophone')], default='francophone', max_length=12),
        ),
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.CharField(choices=[('6e', '6ème'), ('5e', '5ème'), ('4e', '4ème'), ('3e', '3ème'), ('2nde', 'Seconde'), ('1ere', 'Première'), ('Tle', 'Terminale'), ('Form1', 'Form 1'), ('Form2', 'Form 2'), ('Form3', 'Form 3'), ('Form4', 'Form 4'), ('Form5', 'Form 5'), ('LowerSixth', 'Lower Sixth'), ('UpperSixth', 'Upper Sixth'), ('Univ', 'Université')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cours',
            name='serie',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A4', 'A4'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('TI', 'TI'), ('G', 'G'), ('Science', 'Science'), ('Arts', 'Arts'), ('Commercial', 'Commercial')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='niveau_scolaire',
            field=models.CharField(choices=[('6e', '6ème'), ('5e', '5ème'), ('4e', '4ème'), ('3e', '3ème'), ('2nde', 'Seconde'), ('1ere', 'Première'), ('Tle', 'Terminale'), ('Form1', 'Form 1'), ('Form2', 'Form 2'), ('Form3', 'Form 3'), ('Form4', 'Form 4'), ('Form5', 'Form 5'), ('LowerSixth', 'Lower Sixth'), ('UpperSixth', 'Upper Sixth'), ('Univ', 'Université')], max_length=12),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='serie',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A4', 'A4'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('TI', 'TI'), ('G', 'G'), ('Science', 'Science'), ('Arts', 'Arts'), ('Commercial', 'Commercial')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='epreuves',
            name='niveau',
            field=models.CharField(choices=[('6e', '6ème'), ('5e', '5ème'), ('4e', '4ème'), ('3e', '3ème'), ('2nde', 'Seconde'), ('1ere', 'Première'), ('Tle', 'Terminale'), ('Form1', 'Form 1'), ('Form2', 'Form 2'), ('Form3', 'Form 3'), ('Form4', 'Form 4'), ('Form5', 'Form 5'), ('LowerSixth', 'Lower Sixth'), ('UpperSixth', 'Upper Sixth'), ('Univ', 'Université')], max_length=10),
        ),
        migrations.AlterField(
            model_name='epreuves',
            name='serie',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A4', 'A4'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('TI', 'TI'), ('G', 'G'), ('Science', 'Science'), ('Arts', 'Arts'), ('Commercial', 'Commercial')], max_length=10, null=True),
        ),
    ]
