# Generated by Django 6.0.4 on 2026-06-16 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_eleves_systeme_alter_cours_niveau_alter_cours_serie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAdmin',
            fields=[
                ('id_journal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('cible_type', models.CharField(blank=True, max_length=60, null=True)),
                ('cible_id', models.CharField(blank=True, max_length=80, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Action d'administration",
                'verbose_name_plural': "Journal d'administration",
                'db_table': 'journal_admin',
                'ordering': ['-date'],
            },
        ),
    ]
