# Generated by Django 6.0.4 on 2026-06-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_journaladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lacunes',
            name='facilite',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Facteur de facilité SM-2 (>= 1.3).', max_digits=4),
        ),
        migrations.AddField(
            model_name='lacunes',
            name='intervalle_jours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lacunes',
            name='prochaine_revision',
            field=models.DateField(blank=True, help_text='Date à laquelle la notion doit être revue.', null=True),
        ),
        migrations.AddField(
            model_name='lacunes',
            name='repetitions',
            field=models.PositiveSmallIntegerField(default=0, help_text='Nb de révisions réussies consécutives.'),
        ),
    ]
