# Generated by Django 6.0.4 on 2026-06-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_lacunes_facilite_lacunes_intervalle_jours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageschatbot',
            name='utile',
            field=models.BooleanField(blank=True, help_text="Retour de l'élève sur une réponse de l'assistant (👍/👎).", null=True),
        ),
    ]
